DEBUG = True
SECRET_KEY = 'd9cc48b17dff38560f78ef026e41a90b'
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_ECHO = True

SECURITY_URL_PREFIX = '/admin'
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_PASSWORD_SALT = 'ATGUOHAELKiubahiughaerGOJAEGj'

# Flask-Security URLs, overridden because they don't put a / at the end
SECURITY_LOGIN_URL = '/login/'
SECURITY_LOGOUT_URL = '/logout/'
SECURITY_REGISTER_URL = '/register/'

SECURITY_POST_LOGIN_VIEW = '/admin/'
SECURITY_POST_LOGOUT_VIEW = '/admin'
SECURITY_POST_REGISTER_VIEW = '/admin/'

# Flask-Security features
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
